AudioContext "interrupted" state
WebAudio/web-audio-api pull request #2611
Opened 2024-11-09 01:52 UTC by gabrielsanbrito

This PR adds the specification to the AudioContext "interrupted" state. This change does not have Web Platform Tests, because web pages are not able to trigger interruptions themselves. Starting an interruption is a prerogative of the user agent.

Explainer: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/AudioContextInterruptedState/explainer.md

2024-11-10 23:36 UTC, chrisguttandin commented on index.bs
> +                1. Queue a media element task</a> to execute the following steps:
```suggestion
                1. <a href="https://html.spec.whatwg.org/multipage/media.html#queue-a-media-element-task">Queue a media element task</a> to execute the following steps:
```

Some parts of the spec use `[=Queue a media element task=]` instead. But I don't know which one is preferable. Maybe it depends on the context.

2024-11-14 17:52 UTC, hoch commented
FYI @youennf - here's the interrupted state spec work for AudioContext.

2025-02-24 21:53 UTC, gabrielsanbrito commented on index.bs
> +                1. Queue a media element task</a> to execute the following steps:
Do you want me to change all the other occurrences? I mean the other places not necessarily related to this PR.

2025-02-24 22:49 UTC, gabrielsanbrito commented on index.bs
> +            2. Let <var>promise</var> be a new Promise.
Done!

2025-02-24 22:50 UTC, gabrielsanbrito commented on index.bs
> +<h3 id="interruption-handling">Handling an interruption on the {{AudioContext}}</h3>
I have wrapped all the modified lines to be max 80 characters in length

2025-02-24 22:50 UTC, hoch commented
@gabrielsanbrito You don't have to correct all instances in the entire document, but I think it makes sense to clean up the section (e.g. this specific algorithm) that we're working on.

2025-02-24 22:59 UTC, hoch approved these changes
LGTM with nits

Let's wait for the review from @padenot and @chrisguttandin.

2025-02-24 22:59 UTC, hoch commented on index.bs
> +VoIP application.
> This could happen when there is an incoming call from a
VoIP application.

Not sure if this sentence is necessary. Perhaps it's better to make it non-normative note with actual examples? (e.g. phone call, etc)

2025-02-24 22:59 UTC, hoch commented on index.bs
> +The {{AudioContext}} |audioContext| performs the following steps on the
`|audioContext|` to `|context|` to make it simple and terse. I also think this is consistent with other instances in the spec.

2025-02-24 22:59 UTC, hoch commented on index.bs
> +VoIP application.
We have a non-normative note below, so perhaps we can just cut the sentence out.

2025-02-25 00:11 UTC, gabrielsanbrito commented on index.bs
> +VoIP application.
Removed it. Thanks!

2025-02-25 00:12 UTC, gabrielsanbrito commented on index.bs
> +The {{AudioContext}} |audioContext| performs the following steps on the
Done!

2025-03-14 10:40 UTC, padenot requested changes
Looks good, some comments though.

2025-03-14 10:40 UTC, padenot commented on index.bs
> +    1. Abort these steps.
No sublist when doing this, just inline the substep.

2025-03-14 10:40 UTC, padenot commented on index.bs
> +When an [=interruption=] ends, the user agent must <a>queue a control message</a>
must all caps, it's a normative requirement.

2025-03-14 10:40 UTC, padenot commented on index.bs
> +<dfn lt="linear PCM">Linear pulse code modulation</dfn>
What is that doing here?

2025-03-14 10:40 UTC, padenot commented on index.bs
> +    1. Abort these steps.
Same, inline this.

2025-03-14 10:40 UTC, padenot commented on index.bs
> +    and {{AudioContext/resume}} was called during the [=interruption=]:
We want a state for this. Store the "previous state" in a private slot and reference it. This way, it's clear what happens, we can describe it algorithmically.

2025-03-15 05:17 UTC, gabrielsanbrito commented on index.bs
> +    1. Abort these steps.
Done!

2025-03-15 05:17 UTC, gabrielsanbrito commented on index.bs
> +    1. Abort these steps.
Done!

2025-03-15 05:18 UTC, gabrielsanbrito commented on index.bs
> +When an [=interruption=] ends, the user agent must <a>queue a control message</a>
Done! Also modified the other one for the interruption start.

2025-03-15 05:19 UTC, gabrielsanbrito commented on index.bs
> +<dfn lt="linear PCM">Linear pulse code modulation</dfn>
Whoops... I forgot to remove. I pasted there at the time to remember the `<dfn></dfn>` syntax.

2025-03-15 05:26 UTC, gabrielsanbrito commented on index.bs
> +    and {{AudioContext/resume}} was called during the [=interruption=]:
Sounds good. Thanks! I wrote the algorithms like this because I remember that we wanted to be more handwavy with respect to how these states are managed by the UA. But I like to be able to have the clear algorithm steps. 

To address that, I created a new `BaseAudioContext` private slot called `[[interrupt end return state]]`. I don't know if this is the best name, but I couldn't think of a better one. I also rewrote the algorithm for the "interruption end" to branch based on the value of `[[interrupt end return state]]`.

2025-03-15 05:38 UTC, gabrielsanbrito commented
@padenot Thanks for the comments! I have finished addressing them. Could you please have another and see if it looks good to you?

2025-03-17 17:05 UTC, padenot approved these changes
Looking good, just a suggestion for the name of the private slot, that could be a tad clearer.

Good to merge with that addressed, thanks for getting this done!

2025-03-17 17:55 UTC, gabrielsanbrito commented on index.bs
> +            1. Set {{[[interrupt end return state]]}} to `null` on |context|.
Sounds good to me. Renamed it. Thanks!

2025-03-17 18:12 UTC, merged

2025-03-17 18:20 UTC, hoch commented
@gabrielsanbrito Could you follow up on this error?

https://github.com/WebAudio/web-audio-api/actions/runs/13906798454/job/38911674468

```
+FATAL ERROR: Line 2005 isn't indented enough (needs 1 indent) to be valid Markdown:
+"steps, returning <var bs-line-number="2005:34">promise</var>."
```

Looks like there's one indentation error to be fixed.

2025-03-17 19:26 UTC, gabrielsanbrito commented
@hoch, @padenot @chrisguttandin  Thanks for reviewing this PR!